#
# available time unit: day(d), hour(h), minute(m), second(s)
# available command: $broadcast (notify all player) or empty
#

# You can create punishment section.
# Placeholders: $broadcast
action:
  group1:
    1:
      - ban $player $reason

    # How much time must pass after add the violation.
    reduce-after: 1m

  group2:
    1:
      - mute $player 10m $reason
    3:
      - mute $player 20m $reason

    reduce-after: 1h

# How much time must pass after inactivity for us to remove the date.
clear-player-data-after: 5d

# Should we send logs when anyone use /punix command
log-in-console: true